/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Documentario10AnosRouteImport } from './routes/documentario-10-anos'
import { Route as AciaalvoRouteImport } from './routes/aciaalvo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspetaculosIndexRouteImport } from './routes/espetaculos.index'
import { Route as EspetaculosOpassageiroRouteImport } from './routes/espetaculos.opassageiro'
import { Route as EspetaculosOmundodegaelRouteImport } from './routes/espetaculos.omundodegael'
import { Route as EspetaculosMeupequenouniversoRouteImport } from './routes/espetaculos.meupequenouniverso'
import { Route as EspetaculosGuardadoemsilencioRouteImport } from './routes/espetaculos.guardadoemsilencio'
import { Route as EspetaculosGalatasRouteImport } from './routes/espetaculos.galatas'
import { Route as EspetaculosEfesoRouteImport } from './routes/espetaculos.efeso'
import { Route as EspetaculosSlugRouteImport } from './routes/espetaculos.$slug'

const Documentario10AnosRoute = Documentario10AnosRouteImport.update({
  id: '/documentario-10-anos',
  path: '/documentario-10-anos',
  getParentRoute: () => rootRouteImport,
} as any)
const AciaalvoRoute = AciaalvoRouteImport.update({
  id: '/aciaalvo',
  path: '/aciaalvo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosIndexRoute = EspetaculosIndexRouteImport.update({
  id: '/espetaculos/',
  path: '/espetaculos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosOpassageiroRoute = EspetaculosOpassageiroRouteImport.update({
  id: '/espetaculos/opassageiro',
  path: '/espetaculos/opassageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosOmundodegaelRoute = EspetaculosOmundodegaelRouteImport.update({
  id: '/espetaculos/omundodegael',
  path: '/espetaculos/omundodegael',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosMeupequenouniversoRoute =
  EspetaculosMeupequenouniversoRouteImport.update({
    id: '/espetaculos/meupequenouniverso',
    path: '/espetaculos/meupequenouniverso',
    getParentRoute: () => rootRouteImport,
  } as any)
const EspetaculosGuardadoemsilencioRoute =
  EspetaculosGuardadoemsilencioRouteImport.update({
    id: '/espetaculos/guardadoemsilencio',
    path: '/espetaculos/guardadoemsilencio',
    getParentRoute: () => rootRouteImport,
  } as any)
const EspetaculosGalatasRoute = EspetaculosGalatasRouteImport.update({
  id: '/espetaculos/galatas',
  path: '/espetaculos/galatas',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosEfesoRoute = EspetaculosEfesoRouteImport.update({
  id: '/espetaculos/efeso',
  path: '/espetaculos/efeso',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosSlugRoute = EspetaculosSlugRouteImport.update({
  id: '/espetaculos/$slug',
  path: '/espetaculos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aciaalvo': typeof AciaalvoRoute
  '/documentario-10-anos': typeof Documentario10AnosRoute
  '/espetaculos/$slug': typeof EspetaculosSlugRoute
  '/espetaculos/efeso': typeof EspetaculosEfesoRoute
  '/espetaculos/galatas': typeof EspetaculosGalatasRoute
  '/espetaculos/guardadoemsilencio': typeof EspetaculosGuardadoemsilencioRoute
  '/espetaculos/meupequenouniverso': typeof EspetaculosMeupequenouniversoRoute
  '/espetaculos/omundodegael': typeof EspetaculosOmundodegaelRoute
  '/espetaculos/opassageiro': typeof EspetaculosOpassageiroRoute
  '/espetaculos/': typeof EspetaculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aciaalvo': typeof AciaalvoRoute
  '/documentario-10-anos': typeof Documentario10AnosRoute
  '/espetaculos/$slug': typeof EspetaculosSlugRoute
  '/espetaculos/efeso': typeof EspetaculosEfesoRoute
  '/espetaculos/galatas': typeof EspetaculosGalatasRoute
  '/espetaculos/guardadoemsilencio': typeof EspetaculosGuardadoemsilencioRoute
  '/espetaculos/meupequenouniverso': typeof EspetaculosMeupequenouniversoRoute
  '/espetaculos/omundodegael': typeof EspetaculosOmundodegaelRoute
  '/espetaculos/opassageiro': typeof EspetaculosOpassageiroRoute
  '/espetaculos': typeof EspetaculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aciaalvo': typeof AciaalvoRoute
  '/documentario-10-anos': typeof Documentario10AnosRoute
  '/espetaculos/$slug': typeof EspetaculosSlugRoute
  '/espetaculos/efeso': typeof EspetaculosEfesoRoute
  '/espetaculos/galatas': typeof EspetaculosGalatasRoute
  '/espetaculos/guardadoemsilencio': typeof EspetaculosGuardadoemsilencioRoute
  '/espetaculos/meupequenouniverso': typeof EspetaculosMeupequenouniversoRoute
  '/espetaculos/omundodegael': typeof EspetaculosOmundodegaelRoute
  '/espetaculos/opassageiro': typeof EspetaculosOpassageiroRoute
  '/espetaculos/': typeof EspetaculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aciaalvo'
    | '/documentario-10-anos'
    | '/espetaculos/$slug'
    | '/espetaculos/efeso'
    | '/espetaculos/galatas'
    | '/espetaculos/guardadoemsilencio'
    | '/espetaculos/meupequenouniverso'
    | '/espetaculos/omundodegael'
    | '/espetaculos/opassageiro'
    | '/espetaculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aciaalvo'
    | '/documentario-10-anos'
    | '/espetaculos/$slug'
    | '/espetaculos/efeso'
    | '/espetaculos/galatas'
    | '/espetaculos/guardadoemsilencio'
    | '/espetaculos/meupequenouniverso'
    | '/espetaculos/omundodegael'
    | '/espetaculos/opassageiro'
    | '/espetaculos'
  id:
    | '__root__'
    | '/'
    | '/aciaalvo'
    | '/documentario-10-anos'
    | '/espetaculos/$slug'
    | '/espetaculos/efeso'
    | '/espetaculos/galatas'
    | '/espetaculos/guardadoemsilencio'
    | '/espetaculos/meupequenouniverso'
    | '/espetaculos/omundodegael'
    | '/espetaculos/opassageiro'
    | '/espetaculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AciaalvoRoute: typeof AciaalvoRoute
  Documentario10AnosRoute: typeof Documentario10AnosRoute
  EspetaculosSlugRoute: typeof EspetaculosSlugRoute
  EspetaculosEfesoRoute: typeof EspetaculosEfesoRoute
  EspetaculosGalatasRoute: typeof EspetaculosGalatasRoute
  EspetaculosGuardadoemsilencioRoute: typeof EspetaculosGuardadoemsilencioRoute
  EspetaculosMeupequenouniversoRoute: typeof EspetaculosMeupequenouniversoRoute
  EspetaculosOmundodegaelRoute: typeof EspetaculosOmundodegaelRoute
  EspetaculosOpassageiroRoute: typeof EspetaculosOpassageiroRoute
  EspetaculosIndexRoute: typeof EspetaculosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documentario-10-anos': {
      id: '/documentario-10-anos'
      path: '/documentario-10-anos'
      fullPath: '/documentario-10-anos'
      preLoaderRoute: typeof Documentario10AnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aciaalvo': {
      id: '/aciaalvo'
      path: '/aciaalvo'
      fullPath: '/aciaalvo'
      preLoaderRoute: typeof AciaalvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/': {
      id: '/espetaculos/'
      path: '/espetaculos'
      fullPath: '/espetaculos/'
      preLoaderRoute: typeof EspetaculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/opassageiro': {
      id: '/espetaculos/opassageiro'
      path: '/espetaculos/opassageiro'
      fullPath: '/espetaculos/opassageiro'
      preLoaderRoute: typeof EspetaculosOpassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/omundodegael': {
      id: '/espetaculos/omundodegael'
      path: '/espetaculos/omundodegael'
      fullPath: '/espetaculos/omundodegael'
      preLoaderRoute: typeof EspetaculosOmundodegaelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/meupequenouniverso': {
      id: '/espetaculos/meupequenouniverso'
      path: '/espetaculos/meupequenouniverso'
      fullPath: '/espetaculos/meupequenouniverso'
      preLoaderRoute: typeof EspetaculosMeupequenouniversoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/guardadoemsilencio': {
      id: '/espetaculos/guardadoemsilencio'
      path: '/espetaculos/guardadoemsilencio'
      fullPath: '/espetaculos/guardadoemsilencio'
      preLoaderRoute: typeof EspetaculosGuardadoemsilencioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/galatas': {
      id: '/espetaculos/galatas'
      path: '/espetaculos/galatas'
      fullPath: '/espetaculos/galatas'
      preLoaderRoute: typeof EspetaculosGalatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/efeso': {
      id: '/espetaculos/efeso'
      path: '/espetaculos/efeso'
      fullPath: '/espetaculos/efeso'
      preLoaderRoute: typeof EspetaculosEfesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/$slug': {
      id: '/espetaculos/$slug'
      path: '/espetaculos/$slug'
      fullPath: '/espetaculos/$slug'
      preLoaderRoute: typeof EspetaculosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AciaalvoRoute: AciaalvoRoute,
  Documentario10AnosRoute: Documentario10AnosRoute,
  EspetaculosSlugRoute: EspetaculosSlugRoute,
  EspetaculosEfesoRoute: EspetaculosEfesoRoute,
  EspetaculosGalatasRoute: EspetaculosGalatasRoute,
  EspetaculosGuardadoemsilencioRoute: EspetaculosGuardadoemsilencioRoute,
  EspetaculosMeupequenouniversoRoute: EspetaculosMeupequenouniversoRoute,
  EspetaculosOmundodegaelRoute: EspetaculosOmundodegaelRoute,
  EspetaculosOpassageiroRoute: EspetaculosOpassageiroRoute,
  EspetaculosIndexRoute: EspetaculosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
