/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EspetaculosRouteImport } from './routes/espetaculos'
import { Route as Documentario10AnosRouteImport } from './routes/documentario-10-anos'
import { Route as AciaalvoRouteImport } from './routes/aciaalvo'
import { Route as IndexRouteImport } from './routes/index'

const EspetaculosRoute = EspetaculosRouteImport.update({
  id: '/espetaculos',
  path: '/espetaculos',
  getParentRoute: () => rootRouteImport,
} as any)
const Documentario10AnosRoute = Documentario10AnosRouteImport.update({
  id: '/documentario-10-anos',
  path: '/documentario-10-anos',
  getParentRoute: () => rootRouteImport,
} as any)
const AciaalvoRoute = AciaalvoRouteImport.update({
  id: '/aciaalvo',
  path: '/aciaalvo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aciaalvo': typeof AciaalvoRoute
  '/documentario-10-anos': typeof Documentario10AnosRoute
  '/espetaculos': typeof EspetaculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aciaalvo': typeof AciaalvoRoute
  '/documentario-10-anos': typeof Documentario10AnosRoute
  '/espetaculos': typeof EspetaculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aciaalvo': typeof AciaalvoRoute
  '/documentario-10-anos': typeof Documentario10AnosRoute
  '/espetaculos': typeof EspetaculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aciaalvo' | '/documentario-10-anos' | '/espetaculos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aciaalvo' | '/documentario-10-anos' | '/espetaculos'
  id: '__root__' | '/' | '/aciaalvo' | '/documentario-10-anos' | '/espetaculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AciaalvoRoute: typeof AciaalvoRoute
  Documentario10AnosRoute: typeof Documentario10AnosRoute
  EspetaculosRoute: typeof EspetaculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/espetaculos': {
      id: '/espetaculos'
      path: '/espetaculos'
      fullPath: '/espetaculos'
      preLoaderRoute: typeof EspetaculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentario-10-anos': {
      id: '/documentario-10-anos'
      path: '/documentario-10-anos'
      fullPath: '/documentario-10-anos'
      preLoaderRoute: typeof Documentario10AnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aciaalvo': {
      id: '/aciaalvo'
      path: '/aciaalvo'
      fullPath: '/aciaalvo'
      preLoaderRoute: typeof AciaalvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AciaalvoRoute: AciaalvoRoute,
  Documentario10AnosRoute: Documentario10AnosRoute,
  EspetaculosRoute: EspetaculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
