/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EspetaculosRouteImport } from './routes/espetaculos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspetaculosSlugRouteImport } from './routes/espetaculos.$slug'

const EspetaculosRoute = EspetaculosRouteImport.update({
  id: '/espetaculos',
  path: '/espetaculos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosSlugRoute = EspetaculosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EspetaculosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/espetaculos': typeof EspetaculosRouteWithChildren
  '/espetaculos/$slug': typeof EspetaculosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/espetaculos': typeof EspetaculosRouteWithChildren
  '/espetaculos/$slug': typeof EspetaculosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/espetaculos': typeof EspetaculosRouteWithChildren
  '/espetaculos/$slug': typeof EspetaculosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/espetaculos' | '/espetaculos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/espetaculos' | '/espetaculos/$slug'
  id: '__root__' | '/' | '/espetaculos' | '/espetaculos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspetaculosRoute: typeof EspetaculosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/espetaculos': {
      id: '/espetaculos'
      path: '/espetaculos'
      fullPath: '/espetaculos'
      preLoaderRoute: typeof EspetaculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/$slug': {
      id: '/espetaculos/$slug'
      path: '/$slug'
      fullPath: '/espetaculos/$slug'
      preLoaderRoute: typeof EspetaculosSlugRouteImport
      parentRoute: typeof EspetaculosRoute
    }
  }
}

interface EspetaculosRouteChildren {
  EspetaculosSlugRoute: typeof EspetaculosSlugRoute
}

const EspetaculosRouteChildren: EspetaculosRouteChildren = {
  EspetaculosSlugRoute: EspetaculosSlugRoute,
}

const EspetaculosRouteWithChildren = EspetaculosRoute._addFileChildren(
  EspetaculosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspetaculosRoute: EspetaculosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
